### ISSUE TITLE
add countdown timer to washer

### ISSUE THREAD

**Issue by 98sean98** [rcltech/sls#3]
frontend:
add timer beneath each washer

backend:
micropython - add time when washer button has been pressed, correctly pass data to firebase
react - get time data from firebase, create logic to calculate time remaining

**Comment by 98sean98** [comment]
> pushed a commit to washer-timer branch, added timer logic to micropython

<sub>[View in Slack](https://rctechclub.slack.com/archives/CFJ8V5ELS/p1565841954001200)</sub>

**Comment by utkarsh867** [comment]
we will probably never make this feature.
